# Generated by Django 3.2.6 on 2021-08-28 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_operation_sender_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='receiver_account',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='receiver_account', to='api.account'),
        ),
    ]
