# Generated by Django 3.2.6 on 2021-08-29 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210828_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='deposit_address',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
    ]
